### ISSUE TITLE
License information  not updated

### ISSUE THREAD

**Issue by 27Gemini** [clearlydefined/curated-data#18331]
After this PR went through our missing license information for amcharts did not update
https://github.com/clearlydefined/curated-data/pull/18060

Our alerts page still says Missing License information.
 Same for few other components like 
amstock3
https://github.com/clearlydefined/curated-data/pull/18059

Cumulus.InfrastructureContracts
https://github.com/clearlydefined/curated-data/pull/18061

**Comment by capfei** [comment]
Closing since the license information is now updated.
