### ISSUE TITLE
License info still not updated

### ISSUE THREAD

**Issue by 27Gemini** [clearlydefined/curated-data#20534]
After this PR went through our missing license information for angula rdid not update
https://github.com/clearlydefined/curated-data/pull/20476

Our alerts page still says Missing License information.

**Comment by lumenCodes** [comment]
Hello @27Gemini please can I get more context on this issue and possibly how to solve it.?

**Comment by capfei** [comment]
Closing since this is not an issue with ClearlyDefined. License is showing correctly on the site.
https://clearlydefined.io/definitions/nuget/nuget/-/angularjs/1.8.0
