### ISSUE TITLE
not found golang packages

### ISSUE THREAD

**Issue by gouslu** [clearlydefined/curated-data#24490]
I am getting 404 for the packages below. Can this be fixed? Is there anything I can do to help?

Status | Dependency | URL
-- | -- | --
NOT FOUND | github.com/aws/aws-sdk-go-v2/feature/ec2/imds@v1.6.0 | https://api.clearlydefined.io/definitions/go/golang/github.com%2faws%2faws-sdk-go-v2%2ffeature%2fec2%2fimds/v1.6.0
NOT FOUND | github.com/aws/aws-sdk-go-v2/service/internal/presigned-url@v1.3.2 | https://api.clearlydefined.io/definitions/go/golang/github.com%2faws%2faws-sdk-go-v2%2fservice%2finternal%2fpresigned-url/v1.3.2
NOT FOUND | github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/jaeger@v0.68.0 | https://api.clearlydefined.io/definitions/go/golang/github.com%2fopen-telemetry%2fopentelemetry-collector-contrib%2fpkg%2ftranslator%2fjaeger/v0.68.0
NOT FOUND | github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.73.0 | https://api.clearlydefined.io/definitions/go/golang/github.com%2fopen-telemetry%2fopentelemetry-collector-contrib%2fpkg%2ftranslator%2fprometheus/v0.73.0
NOT FOUND | github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheusremotewrite@v0.73.0 | https://api.clearlydefined.io/definitions/go/golang/github.com%2fopen-telemetry%2fopentelemetry-collector-contrib%2fpkg%2ftranslator%2fprometheusremotewrite/v0.73.0
NOT FOUND | go.opencensus.io@v0.24.0 | https://api.clearlydefined.io/definitions/go/golang/go.opencensus.io/v0.24.0
NOT FOUND | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.40.0 | https://api.clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fcontrib%2finstrumentation%2fgoogle.golang.org%2fgrpc%2fotelgrpc/v0.40.0
NOT FOUND | go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0 | https://api.clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fcontrib%2finstrumentation%2fnet%2fhttp%2fotelhttp/v0.40.0
NOT FOUND | go.opentelemetry.io/otel/exporters/otlp/internal/retry@v1.11.2 | https://api.clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fotel%2fexporters%2fotlp%2finternal%2fretry/v1.11.2
NOT FOUND | go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc@v1.11.2 | https://api.clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fotel%2fexporters%2fotlp%2fotlptrace%2fotlptracegrpc/v1.11.2
NOT FOUND | go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp@v1.11.2 | https://api.clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fotel%2fexporters%2fotlp%2fotlptrace%2fotlptracehttp/v1.11.2

**Comment by mpcen** [comment]
@qtomlinson

**Comment by mattsains** [comment]
I've been having a problem harvesting packages like these as well. I tried to do specifically github.com/open-telemetry/opentelemetry-collector like this:

![image](https://github.com/clearlydefined/curated-data/assets/2083713/4b182a4c-d78a-45d6-a355-26961c9a3ec5)

But after multiple days, the golang package page still shows it as not harvested:

https://clearlydefined.io/definitions/go/golang/github.com%2fopen-telemetry/opentelemetry-collector/v0.82.0

![image](https://github.com/clearlydefined/curated-data/assets/2083713/69237519-7e27-4184-9c2d-14698dd6b578)

Is there a different/correct way to do this that I don't know about?

**Comment by mattsains** [comment]
ok, that package just spontaneously became harvested. I'll keep an eye on the other packages I've been testing with to see whether they resolve themselves too

**Comment by mattsains** [comment]
Yesterday, I submitted a request like this:

```
[{"tool":"package", "coordinates":"go/golang/go.opentelemetry.io/collector/component/v0.82.0"}]
```

but this page hasn't been updated today: https://clearlydefined.io/definitions/go/golang/go.opentelemetry.io%2fcollector%2fcomponent/v0.82.0
