### ISSUE TITLE
Question: Does clearlydefined analyze go-lang dependency transitively?

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [clearlydefined/curated-data#8151]
I know that clearlydefined analyzes npm dependencies transitively. What about go-lang dependencies? Does clearlydefined analyze go-lang dependency  transitively or developer should provide each dependency separately for analyzing?

**Comment by fossygirl** [comment]
@AndrienkoAleksandr We do not currently have Go support in ClearlyDefined. I also want to clarify that ClearlyDefined does not do any kind of dependency analysis. We consider all component individually and provide our definitions on a per-component basis, completely independent of any dependencies.

**Comment by AndrienkoAleksandr** [comment]
>  We do not currently have Go support in ClearlyDefined

Hmm..., thanks. Sorry, but how was https://clearlydefined.io/?maxLicensedScore=70&sort=effectiveScore&name=go-winio golang project applied to the checked list?

**Comment by fossygirl** [comment]
Those are all git packages we've scanned. If components we harvest have reference to their source in git/GitHub, we queue up a harvest of the source as well. So it looks like that was in git somewhere.

**Comment by AndrienkoAleksandr** [comment]
Thanks for info.
