### ISSUE TITLE
"Contribute" button on https://clearlydefined.io/

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/curated-data#839]
I've declared a bunch of licenses and hit the "Contribute" button and received no indication anything went through and did not receive an email from the clearlydefinedbot that anything happened.  Also, I do not see what I contributed here: https://github.com/clearlydefined/curated-data/pulls..  ?

**Comment by dabutvin** [comment]
@ariel11 thanks for reporting. 

I see your error in the log, the error was `patch.contributionInfo` was not defined. Not sure how that is possible. 

We just pushed a bunch of changes to the website and I was able to submit a curation.

When you get a chance can you try again and see if it happens still?
Were you logged in at the time?
If it does happen again, can you take a quick screenshot and paste it here?

**Comment by fossygirl** [comment]
@ariel11 Closing this since it looks like it wasn't repeatable, but please do reopen if it happens again.
