### ISSUE TITLE
Google.Protobuf.Tools NuGet packages may not be BSD 3-Clause only

### ISSUE THREAD

**Issue by chwarr** [clearlydefined/curated-data#8958]
The [Google.Protobuf.Tools NuGet package](https://www.nuget.org/packages/Google.Protobuf.Tools/) links to https://github.com/protocolbuffers/protobuf/blob/master/LICENSE for its license. (I looked at [version 3.14 in particular](https://www.nuget.org/packages/Google.Protobuf.Tools/3.14.0).) This LICENSE file does not exactly match the 3-clause BSD license. It includes the following additional text at the end of the license ([permalink to the revision I copied this from](https://github.com/protocolbuffers/protobuf/blob/9647a7c2356a9529754c07235a2877ee676c2fd0/LICENSE)):

> Code generated by the Protocol Buffer compiler is owned by the owner
> of the input file used when generating it.  This code is not
> standalone and requires a support library to be linked with it.  This
> support library is itself covered by the above license.

Is this still considered a 3-clause BSD license? If not, does this warrant its own license or its own exception?

The [SPDX Matching Guidelines v2.1](https://spdx.dev/license-list/matching-guidelines/) say:

> 2.1.2 Guideline:   No Additional Text
> 
> Matched text should only include that found in the vetted license or exception text. Where a license or exception found includes additional text or clauses, this should not be considered a match.

(Is there a better venue to raise these sort of discrepancies?)

**Comment by capfei** [comment]
If I was curating this, I would curate it as BSD-3-Clause. To me, the last bit reads as an FYI instead of being a part of the license text itself.

**Comment by chwarr** [comment]
Sounds good to me. Thanks.
